--Tables and sequences creation

-- 1. PRODUCT_ID sequence and PRODUCTS table
drop sequence PRODUCT_ID_SEQ;

CREATE sequence PRODUCT_ID_SEQ;
CREATE TABLE PRODUCTS (
	Id INT DEFAULT PRODUCT_ID_SEQ.NEXTVAL NOT NULL,
  name NVARCHAR2(200) NOT NULL,
	price DECIMAL(10) NOT NULL,
  manufacturer_id INT NOT NULL,
  supplier_id INT NOT NULL,
  amount int NOT NULL,
  product_type int NOT NULL,
	constraint PRODUCT_PK PRIMARY KEY (Id));
     
-- 2. MANUFACTURER_ID sequence and MANUFACTURERS table
drop sequence MANUFACTURER_ID_SEQ;

CREATE sequence MANUFACTURER_ID_SEQ;
CREATE TABLE MANUFACTURERS (
	Id INT DEFAULT MANUFACTURER_ID_SEQ.NEXTVAL NOT NULL,
	?ompany_name NVARCHAR2(200) NOT NULL,
	adress NVARCHAR2(200) NOT NULL,
	phone_number NVARCHAR2(50) NOT NULL,
	constraint MANUFACTURER_PK PRIMARY KEY (Id));
    
-- 3. SUPPLIER_ID sequence and SUPPLIERS table
drop sequence SUPPLIER_ID_SEQ;

CREATE sequence SUPPLIER_ID_SEQ;
CREATE TABLE SUPPLIERS (
	Id INT DEFAULT SUPPLIER_ID_SEQ.NEXTVAL NOT NULL,
	?ompany_name NVARCHAR2(200) NOT NULL,
	adress NVARCHAR2(200) NOT NULL,
	phone_number NVARCHAR2(50) NOT NULL,
	constraint SUPPLIER_PK PRIMARY KEY (Id));

-- 4. CLIENT_ID sequence and CLIENTS table
drop sequence CLIENT_ID_SEQ;

CREATE sequence CLIENT_ID_SEQ;
CREATE TABLE CLIENTS (
	Id INT DEFAULT CLIENT_ID_SEQ.NEXTVAL NOT NULL,
	nickname NVARCHAR2(200) NOT NULL,
	name NVARCHAR2(50) NOT NULL,
	surname NVARCHAR2(50) NOT NULL,
	patronymic NVARCHAR2(50) NOT NULL,
  email NVARCHAR2(200),
	adress NVARCHAR2(100) NOT NULL,
	phone_number NVARCHAR2(100) UNIQUE NOT NULL,
	constraint CLIENT_PK PRIMARY KEY (id));
  
-- 5. SALESMAN_ID sequence and SALESMEN table
drop sequence SALESMAN_ID_SEQ;

CREATE sequence SALESMAN_ID_SEQ;
CREATE TABLE SALESMEN (
	Id INT DEFAULT SALESMAN_ID_SEQ.NEXTVAL NOT NULL,
	name NVARCHAR2(50) NOT NULL,
	surname NVARCHAR2(50) NOT NULL,
	patronymic NVARCHAR2(50) NOT NULL,
	adress NVARCHAR2(100) NOT NULL,
	phone_number NVARCHAR2(50) UNIQUE NOT NULL,
	constraint SALESMEN_PK PRIMARY KEY (id));
  
-- 6. PRODUCT_TYPE_ID sequence and PRODUCT_TYPES table
drop sequence PRODUCT_TYPE_ID_SEQ;

CREATE sequence PRODUCT_TYPE_ID_SEQ;
CREATE TABLE PRODUCT_TYPES (
	Id INT DEFAULT PRODUCT_TYPE_ID_SEQ.NEXTVAL NOT NULL,
	type NVARCHAR2(200) NOT NULL,
	constraint PRODUCT_TYPES_PK PRIMARY KEY (id));
  
-- 7. STORE_ID sequence and STORES table
drop sequence STORE_ID_SEQ;

CREATE sequence STORE_ID_SEQ;
CREATE TABLE STORES (
	Id INT DEFAULT STORE_ID_SEQ.NEXTVAL NOT NULL,
	address NVARCHAR2(200) NOT NULL,
	constraint STORES_PK PRIMARY KEY (id));
  
-- 8. ORDER_NUMBER sequence and ORDERS table
drop sequence ORDER_NUMBER_SEQ;

CREATE sequence ORDER_NUMBER_SEQ;
CREATE TABLE ORDERS (
	order_number INT DEFAULT ORDER_NUMBER_SEQ.NEXTVAL NOT NULL,
	salesman_id int NOT NULL,
  client_id int NOT NULL,
  product_id int NOT NULL,
  amount int NOT NULL,
  store_id int NOT NULL,
  order_date date NOT NULL,  
	constraint ORDERS_PK PRIMARY KEY (order_number));

ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_FK1 FOREIGN KEY (manufacturer_id) 
  REFERENCES MANUFACTURERS(Id);
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_FK2 FOREIGN KEY (supplier_id) 
  REFERENCES SUPPLIERS(Id);
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_FK3 FOREIGN KEY (product_type) 
  REFERENCES PRODUCT_TYPES(Id);
  
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK1 FOREIGN KEY (salesman_id) 
  REFERENCES SALESMEN(Id);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK2 FOREIGN KEY (client_id) 
  REFERENCES CLIENTS(Id);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK3 FOREIGN KEY (store_id) 
  REFERENCES STORES(Id);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK4 FOREIGN KEY (product_id) 
  REFERENCES PRODUCTS(Id);
  
drop table ORDERS;
drop table PRODUCTS;
drop table MANUFACTURERS;
drop table SUPPLIERS;
drop table PRODUCT_TYPES;
drop table SALESMEN;
drop table CLIENTS;
drop table STORES;